language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install flake8
script:
  - flake8
  - nosetests -v tests
deploy:
  provider: pypi
  user: wg_webqaa
  password:
    secure: DcVhS0+ivUH80Nod578mpOGw0VWt+IatNnek5ALmMEJstt7NZWVuv8ZpknfLWqEoTGcChDcmqnM59uTwEykUqJxQY4PPlKab3sfntp08hTqssIJ2ikvRBeIrTsaUGyzu+jpa4x1bDRtQmcxzjH6JtT45QsCHnvWvOpjpTI34X/w=
  on:
    tags: true
    distributions: sdist
    repo: wgnet/grail
